Handle `null` `Intent` in `ensureDeeplinkStartLocationValid`
Fixes this error which was triggered by `navigator.reset()` in a `HotwireFragment`

```
  java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null
  object reference
                                                                                                          at
  dev.hotwire.navigation.navigator.NavigatorHost.ensureDeeplinkStartLocationValid(NavigatorHost.kt:82)
```